export const dummyUsers = {
  examiner1: {
    id: 'examiner-1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@university.edu',
    role: 'examiner',
    institute: 'State University',
    phone: '+1-555-0101',
  },
  candidate1: {
    id: 'candidate-1',
    name: 'John Smith',
    email: 'john.smith@student.edu',
    role: 'candidate',
    institute: 'State University',
    phone: '+1-555-0102',
    guardianName: 'Michael Smith',
    guardianPhone: '+1-555-0103',
  },
  candidate2: {
    id: 'candidate-2',
    name: 'Emily Davis',
    email: 'emily.davis@student.edu',
    role: 'candidate',
    institute: 'State University',
    phone: '+1-555-0104',
    guardianName: 'Patricia Davis',
    guardianPhone: '+1-555-0105',
  },
  candidate3: {
    id: 'candidate-3',
    name: 'Michael Chen',
    email: 'michael.chen@student.edu',
    role: 'candidate',
    institute: 'State University',
    phone: '+1-555-0106',
    guardianName: 'David Chen',
    guardianPhone: '+1-555-0107',
  },
  candidate4: {
    id: 'candidate-4',
    name: 'Sophia Martinez',
    email: 'sophia.martinez@student.edu',
    role: 'candidate',
    institute: 'State University',
    phone: '+1-555-0108',
    guardianName: 'Carlos Martinez',
    guardianPhone: '+1-555-0109',
  },
  candidate5: {
    id: 'candidate-5',
    name: 'Aisha Patel',
    email: 'aisha.patel@student.edu',
    role: 'candidate',
    institute: 'State University',
    phone: '+1-555-0110',
    guardianName: 'Rajesh Patel',
    guardianPhone: '+1-555-0111',
  },
};

export const dummyHalls = [
  {
    id: 'hall-1',
    name: 'Main Hall A',
    code: 'MAIN24',
    hallCode: 'MAIN24', // Unique hall code for candidates to join
    capacity: 50,
    occupied: 2,
    examinerId: 'examiner-1',
    candidates: ['candidate-1', 'candidate-2'],
    createdAt: new Date('2024-02-01'),
    status: 'active',
  },
  {
    id: 'hall-2',
    name: 'Computer Lab B',
    code: 'COMP24',
    hallCode: 'COMP24',
    capacity: 30,
    occupied: 3,
    examinerId: 'examiner-1',
    candidates: ['candidate-3', 'candidate-4', 'candidate-5'],
    createdAt: new Date('2024-02-05'),
    status: 'active',
  },
  {
    id: 'hall-3',
    name: 'Science Building C',
    code: 'SCIENCE01',
    hallCode: 'SCIENCE01',
    capacity: 40,
    occupied: 0,
    examinerId: 'examiner-1',
    candidates: [],
    createdAt: new Date('2024-02-10'),
    status: 'inactive',
  },
];

export const dummyExams = [
  {
    id: 'exam-1',
    title: 'Physics Mid-Term Exam',
    hallId: 'hall-1',
    examinerId: 'examiner-1',
    totalMarks: 100,
    duration: 120, // in minutes
    status: 'scheduled',
    scheduledDate: new Date('2024-02-20'),
    sections: ['section-1', 'section-2'],
    description: 'Comprehensive physics examination covering mechanics and thermodynamics',
  },
  {
    id: 'exam-2',
    title: 'Mathematics Final Exam',
    hallId: 'hall-2',
    examinerId: 'examiner-1',
    totalMarks: 100,
    duration: 180,
    status: 'active',
    scheduledDate: new Date('2024-02-22'),
    sections: ['section-3', 'section-4'],
    description: 'Final examination covering algebra and geometry topics',
  },
  {
    id: 'exam-3',
    title: 'Chemistry Mid-Term',
    hallId: 'hall-2',
    examinerId: 'examiner-1',
    totalMarks: 80,
    duration: 90,
    status: 'completed',
    scheduledDate: new Date('2024-02-15'),
    sections: ['section-5'],
    description: 'Chemistry examination on atomic structure and bonding',
  },
];

export const dummySections = [
  {
    id: 'section-1',
    examId: 'exam-1',
    title: 'Section A: Objective',
    type: 'objective',
    totalMarks: 50,
    questions: ['q-1', 'q-2', 'q-3'],
    order: 1,
  },
  {
    id: 'section-2',
    examId: 'exam-1',
    title: 'Section B: Reasoning',
    type: 'subjective',
    totalMarks: 50,
    questions: ['q-4', 'q-5'],
    order: 2,
  },
  {
    id: 'section-3',
    examId: 'exam-2',
    title: 'Section A: Algebra',
    type: 'mixed',
    totalMarks: 50,
    questions: ['q-6', 'q-7', 'q-8'],
    order: 1,
  },
  {
    id: 'section-4',
    examId: 'exam-2',
    title: 'Section B: Geometry',
    type: 'subjective',
    totalMarks: 50,
    questions: ['q-9', 'q-10'],
    order: 2,
  },
  {
    id: 'section-5',
    examId: 'exam-3',
    title: 'Section A: Chemistry',
    type: 'objective',
    totalMarks: 80,
    questions: ['q-11', 'q-12', 'q-13', 'q-14'],
    order: 1,
  },
];

export const dummyQuestions = [
  {
    id: 'q-1',
    sectionId: 'section-1',
    text: 'What is the SI unit of force?',
    type: 'mcq',
    marks: 10,
    options: ['q1-opt-1', 'q1-opt-2', 'q1-opt-3', 'q1-opt-4'],
    correctAnswer: 'q1-opt-2',
  },
  {
    id: 'q-2',
    sectionId: 'section-1',
    text: 'Calculate the velocity of an object with mass 5 kg under force of 20 N.',
    type: 'numerical',
    marks: 20,
    options: [],
    correctAnswer: '4 m/s',
  },
  {
    id: 'q-3',
    sectionId: 'section-1',
    text: 'Define the first law of motion.',
    type: 'mcq',
    marks: 10,
    options: ['q3-opt-1', 'q3-opt-2', 'q3-opt-3', 'q3-opt-4'],
    correctAnswer: 'q3-opt-1',
  },
  {
    id: 'q-4',
    sectionId: 'section-2',
    text: 'Explain the law of conservation of momentum. Show all working.',
    type: 'subjective',
    marks: 25,
    options: [],
    correctAnswer: 'The total momentum of a system remains constant in absence of external forces.',
    allowHandwritten: true,
  },
  {
    id: 'q-5',
    sectionId: 'section-2',
    text: 'Derive the relationship between Celsius and Kelvin scales.',
    type: 'subjective',
    marks: 25,
    options: [],
    correctAnswer: 'K = °C + 273.15',
    allowHandwritten: true,
  },
  {
    id: 'q-6',
    sectionId: 'section-3',
    text: 'Solve: 2x + 5 = 15',
    type: 'numerical',
    marks: 10,
    options: [],
    correctAnswer: '5',
  },
  {
    id: 'q-7',
    sectionId: 'section-3',
    text: 'What is the quadratic formula?',
    type: 'mcq',
    marks: 10,
    options: ['q7-opt-1', 'q7-opt-2', 'q7-opt-3', 'q7-opt-4'],
    correctAnswer: 'q7-opt-2',
  },
  {
    id: 'q-8',
    sectionId: 'section-3',
    text: 'Solve the equation step by step: x² - 5x + 6 = 0',
    type: 'subjective',
    marks: 30,
    options: [],
    correctAnswer: 'x = 2 or x = 3',
    allowHandwritten: true,
  },
  {
    id: 'q-9',
    sectionId: 'section-4',
    text: 'Calculate the area of a triangle with base 10 cm and height 5 cm.',
    type: 'numerical',
    marks: 15,
    options: [],
    correctAnswer: '25',
  },
  {
    id: 'q-10',
    sectionId: 'section-4',
    text: 'Prove that the sum of angles in a triangle is 180 degrees.',
    type: 'subjective',
    marks: 35,
    options: [],
    correctAnswer: 'Using parallel line properties and corresponding angles.',
    allowHandwritten: true,
  },
  {
    id: 'q-11',
    sectionId: 'section-5',
    text: 'What is the atomic number of Carbon?',
    type: 'mcq',
    marks: 10,
    options: ['q11-opt-1', 'q11-opt-2', 'q11-opt-3', 'q11-opt-4'],
    correctAnswer: 'q11-opt-2',
  },
  {
    id: 'q-12',
    sectionId: 'section-5',
    text: 'The electron configuration of Oxygen is:',
    type: 'mcq',
    marks: 10,
    options: ['q12-opt-1', 'q12-opt-2', 'q12-opt-3', 'q12-opt-4'],
    correctAnswer: 'q12-opt-1',
  },
  {
    id: 'q-13',
    sectionId: 'section-5',
    text: 'What type of bond is found in NaCl?',
    type: 'numerical',
    marks: 20,
    options: [],
    correctAnswer: 'Ionic bond',
  },
  {
    id: 'q-14',
    sectionId: 'section-5',
    text: 'How many valence electrons does a Silicon atom have?',
    type: 'numerical',
    marks: 20,
    options: [],
    correctAnswer: '4',
  },
];

export const dummyOptions = {
  'q1-opt-1': { id: 'q1-opt-1', text: 'Pascal' },
  'q1-opt-2': { id: 'q1-opt-2', text: 'Newton' },
  'q1-opt-3': { id: 'q1-opt-3', text: 'Joule' },
  'q1-opt-4': { id: 'q1-opt-4', text: 'Watt' },
  'q3-opt-1': { id: 'q3-opt-1', text: 'An object at rest stays at rest unless acted upon by a force' },
  'q3-opt-2': { id: 'q3-opt-2', text: 'Force equals mass times acceleration' },
  'q3-opt-3': { id: 'q3-opt-3', text: 'Every action has an equal and opposite reaction' },
  'q3-opt-4': { id: 'q3-opt-4', text: 'Objects move in a straight line' },
  'q7-opt-1': { id: 'q7-opt-1', text: 'x = a + b + c' },
  'q7-opt-2': { id: 'q7-opt-2', text: 'x = (-b ± √(b² - 4ac)) / 2a' },
  'q7-opt-3': { id: 'q7-opt-3', text: 'x = b² - 4ac' },
  'q7-opt-4': { id: 'q7-opt-4', text: 'x = a² + b²' },
  'q11-opt-1': { id: 'q11-opt-1', text: '5' },
  'q11-opt-2': { id: 'q11-opt-2', text: '6' },
  'q11-opt-3': { id: 'q11-opt-3', text: '7' },
  'q11-opt-4': { id: 'q11-opt-4', text: '8' },
  'q12-opt-1': { id: 'q12-opt-1', text: '1s² 2s² 2p⁴' },
  'q12-opt-2': { id: 'q12-opt-2', text: '1s² 2s² 2p² 3p²' },
  'q12-opt-3': { id: 'q12-opt-3', text: '1s² 2s² 2p³' },
  'q12-opt-4': { id: 'q12-opt-4', text: '1s² 2s² 2p⁵' },
};

export const dummyAttempts = [
  {
    id: 'attempt-1',
    candidateId: 'candidate-1',
    examId: 'exam-1',
    hallId: 'hall-1',
    candidateName: 'John Smith',
    startedAt: new Date('2024-02-20T09:00:00'),
    finishedAt: new Date('2024-02-20T10:59:00'),
    status: 'submitted',
    totalMarks: 78,
    correctAnswers: 4,
    answers: [
      {
        questionId: 'q-1',
        answer: 'q1-opt-2',
        marks: 10,
        isCorrect: true,
      },
      {
        questionId: 'q-2',
        answer: '4 m/s',
        marks: 18,
        isCorrect: false,
      },
      {
        questionId: 'q-3',
        answer: 'The total momentum remains constant.',
        marks: 18,
        isCorrect: false,
      },
      {
        questionId: 'q-4',
        answer: 'q4-opt-3',
        marks: 15,
        isCorrect: true,
      },
      {
        questionId: 'q-5',
        answer: 'K = C + 273',
        marks: 17,
        isCorrect: false,
      },
    ],
  },
  {
    id: 'attempt-2',
    candidateId: 'candidate-2',
    examId: 'exam-1',
    hallId: 'hall-1',
    candidateName: 'Emily Davis',
    startedAt: new Date('2024-02-20T09:15:00'),
    finishedAt: new Date('2024-02-20T11:00:00'),
    status: 'submitted',
    totalMarks: 92,
    correctAnswers: 5,
    answers: [],
  },
  {
    id: 'attempt-3',
    candidateId: 'candidate-3',
    examId: 'exam-1',
    hallId: 'hall-2',
    candidateName: 'Michael Chen',
    startedAt: new Date('2024-02-20T09:30:00'),
    finishedAt: new Date('2024-02-20T10:50:00'),
    status: 'submitted',
    totalMarks: 65,
    correctAnswers: 3,
    answers: [],
  },
];

// Grade distribution data for analytics
export const dummyGradeDistribution = [
  { range: '90-100', count: 2 },
  { range: '80-89', count: 5 },
  { range: '70-79', count: 8 },
  { range: '60-69', count: 4 },
  { range: '50-59', count: 1 },
];

// Leaderboard data
export const dummyLeaderboard = [
  { candidateId: 'candidate-2', candidateName: 'Emily Davis', hallId: 'hall-1', marks: 92, examId: 'exam-1' },
  { candidateId: 'candidate-1', candidateName: 'John Smith', hallId: 'hall-1', marks: 78, examId: 'exam-1' },
  { candidateId: 'candidate-3', candidateName: 'Michael Chen', hallId: 'hall-2', marks: 65, examId: 'exam-1' },
];
